[
  {
    "signature": "java.util.concurrent.CompletionException()",
    "name": "java.util.concurrent.CompletionException",
    "containingClass": {
      "qualifiedName": "java.util.concurrent.CompletionException",
      "name": "CompletionException",
      "isArray": false
    },
    "targetClass": "java.util.concurrent.CompletionException",
    "isVarArgs": false,
    "parameters": [],
    "protocol": {
      "member": "java.util.concurrent.CompletionException()",
      "comment": "Constructs a CompletionException with no detail message. The cause is not initialized, and may subsequently be initialized by a call to method_0 initCause.",
      "kind": "FreeText",
      "condition": ""
    }
  },
  {
    "signature": "java.util.concurrent.CompletionException(java.lang.String message)",
    "name": "java.util.concurrent.CompletionException",
    "containingClass": {
      "qualifiedName": "java.util.concurrent.CompletionException",
      "name": "CompletionException",
      "isArray": false
    },
    "targetClass": "java.util.concurrent.CompletionException",
    "isVarArgs": false,
    "parameters": [
      {
        "type": {
          "qualifiedName": "java.lang.String",
          "name": "String",
          "isArray": false
        },
        "name": "message"
      }
    ],
    "protocol": {
      "member": "java.util.concurrent.CompletionException(java.lang.String message)",
      "comment": "Constructs a CompletionException with the specified detail message. The cause is not initialized, and may subsequently be initialized by a call to method_0 initCause.",
      "kind": "FreeText",
      "condition": ""
    }
  },
  {
    "signature": "java.util.concurrent.CompletionException(java.lang.String message, java.lang.Throwable cause)",
    "name": "java.util.concurrent.CompletionException",
    "containingClass": {
      "qualifiedName": "java.util.concurrent.CompletionException",
      "name": "CompletionException",
      "isArray": false
    },
    "targetClass": "java.util.concurrent.CompletionException",
    "isVarArgs": false,
    "parameters": [
      {
        "type": {
          "qualifiedName": "java.lang.String",
          "name": "String",
          "isArray": false
        },
        "name": "message"
      },
      {
        "type": {
          "qualifiedName": "java.lang.Throwable",
          "name": "Throwable",
          "isArray": false
        },
        "name": "cause"
      }
    ],
    "protocol": {
      "member": "java.util.concurrent.CompletionException(java.lang.String message, java.lang.Throwable cause)",
      "comment": "Constructs a CompletionException with the specified detail message and cause.",
      "kind": "FreeText",
      "condition": ""
    }
  },
  {
    "signature": "java.util.concurrent.CompletionException(java.lang.Throwable cause)",
    "name": "java.util.concurrent.CompletionException",
    "containingClass": {
      "qualifiedName": "java.util.concurrent.CompletionException",
      "name": "CompletionException",
      "isArray": false
    },
    "targetClass": "java.util.concurrent.CompletionException",
    "isVarArgs": false,
    "parameters": [
      {
        "type": {
          "qualifiedName": "java.lang.Throwable",
          "name": "Throwable",
          "isArray": false
        },
        "name": "cause"
      }
    ],
    "protocol": {
      "member": "java.util.concurrent.CompletionException(java.lang.Throwable cause)",
      "comment": "Constructs a CompletionException with the specified cause. The detail message is set to (cause == null ? null : method_0 (which typically contains the class and detail message of {@code cause}).",
      "kind": "FreeText",
      "condition": ""
    }
  }
]